### ISSUE TITLE
MS2000 hardware settings?

### ISSUE THREAD

**Issue by bozoreddev** [inteyes/ReMS2000#3]
### Discussed in https://github.com/inteyes/ReMS2000/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **bozoreddev** January 10, 2023</sup>
Hello,

Downloaded the program, everything on the GUI works and it looks fantastic. However when I try to send sysex to the hardware it says "Synthesizer is not responding". I have the MIDI output set to matching channels on my interface and the MS200B.

![AA74B839-7F71-482A-9F9C-B49245549E1E_4_5005_c](https://user-images.githubusercontent.com/78248006/211690343-c01a0b71-6997-4ed4-8fc5-bcebd70b0f7f.jpeg)
![3D975151-05E5-4D7A-9853-E4C635F87230_4_5005_c](https://user-images.githubusercontent.com/78248006/211690388-e8b2ae83-26e7-4139-92fe-4cfcbb04620d.jpeg)
![CE4958FC-9045-40B3-8B1D-AAD2B686146F_4_5005_c](https://user-images.githubusercontent.com/78248006/211690409-afb3e72b-93e2-461f-aed5-d2d103d84bf2.jpeg)
</div>

**Comment by inteyes** [comment]
Hello, @bozoreddev.

In order this panel to work properly, you have to set both Input and Output MIDI devices.
As far as I can see in the picture, the Input MIDI Device is not set, so this panel does not receive any data from the synthesizer (which is required for some SysEx operations). That's the main reason for the "Synthesizer is not responding" message.

The "[Quick Start](https://github.com/inteyes/ReMS2000#quick-start)" section on the main page of this repository describes the required minimum settings for both the device and the panel, feel free to check it out.

**Comment by bozoreddev** [comment]
Roger that. I’ll retry. ThanksOn Jan 10, 2023, at 23:45, Andrew Ignatyev ***@***.***> wrote:﻿
Hello, @bozoreddev.
In order this panel to work properly, you have to set both Input and Output MIDI devices.
As far as I can see in the picture, the Input MIDI Device is not set, so this panel does not receive any data from the synthesizer (which is required for some SysEx operations). That's the main reason for the "Synthesizer is not responding" message.
The "Quick Start" section on the main page of this repository describes the required minimum settings for both the device and the panel, feel free to check it out.
